[window]
dimensions = { columns = 120, lines = 30 }
padding = { x = 10, y = 10 }
decorations = "Full"

[font]
normal = { family = "Fira Code", style = "Regular" }
size = 12.0

[colors.primary]
background = "#1D1F21"
foreground = "#C5C8C6"
